### ISSUE TITLE
Confirm closing the app if there are active swaps

### ISSUE THREAD

**Issue by sindresorhus** [lukechilds/hyperdex#229]
With a message that the trade might be ruined if you close the app. Sometimes marketmaker can kickstart a interrupted swap, sometimes not. Nobody knows.

https://github.com/lukechilds/hyperdex-bugtracker/issues/1#issuecomment-389810248

> Although there's no real way for us to know if the swap is actually swapping normally or if it's "stuck". But still good to show a warning either way.
> \- @lukechilds

**Comment by lukechilds** [comment]
>the trade might be ruined

According to @jl777, the trade won't be ruined, it should always be reversible. So the next time they start the app, it should try to unwind.

But a warning is still needed, just slightly less alarming wording.

**Comment by sindresorhus** [comment]
> So the next time they start the app, it should try to unwind.

I have yet to see that happen for interrupted swaps though...

**Comment by lukechilds** [comment]
Me too, trying to get more clarification on this.

**Comment by jl777** [comment]
before the first three payments are completed, exiting a swap will in effect cancel it

after bobdeposit, alicepayment, bobpayment, then in vast majority of cases it will complete even after exit and restart. On the bob side, he might find that the bobdeposit was claimed instead of the bobpayment, in that case he will be able to reclaim the bobpayment and alicepayment, so only out the difference between the deposit and payment. That is the incentive for bob to stay online and promptly complete the swap.

https://bitcointalk.org/index.php?topic=1364951 is the thread with all the details on all the things that can happen to the atomic swap.

plz post the swapstatus result for any "forever stuck" swap, I am not seeing such things in a long long time

**Comment by lukechilds** [comment]
I have just successfully unwound a swap 🎉 

@jl777 we haven't done much testing on this due to the difficulty of having to wait for timelocks etc, we're just going on user feedback.

However it looks like a combination of us never using `swapstatus` and the fact that our event listeners get removed on failure so we never get any socket updates, (therefore the GUI never updates even if mm successfully unwinds).

I will try to test this more thoroughly before the public launch. But in one carefully controlled test I just completed I did manage to get a failed swap to rewind.

**Comment by jl777** [comment]
probably a good idea not to remove a listener until the swap achieves .finished

**Comment by sindresorhus** [comment]
@lukechilds How are we going to detect is there are active swaps in progress? It sounds easy, just find the ones that are not failed or completed, but what do we then do about stuck swaps. We don't want to show the warning each time a user closes an app if they have an old stuck swap. We really need to fix the swap handling before this and clear out old stuck swaps that will never unwind.

**Comment by jl777** [comment]
if a swap is pending and the DB/SWAPS files are there, you can exit as when it is running again the files are there. 

one idea is to store the timestamp of when the app is launched and only consider warning users about swaps that did not already exist at that time. that way you only warn users about new swaps that are not finished.

**Comment by lukechilds** [comment]
>How are we going to detect if there are active swaps in progress?

We already store the swap start timestamps so as James suggest we can only warn on incomplete swaps from the current session.

>We really need to fix the swap handling before this and clear out old stuck swaps that will never unwind.

I have an idea in how to better resolve unwinding. I'll work on implementing this after ETH/ERC20 is done.

**Comment by jl777** [comment]
A good way to detect if there are any active swaps is to issue swapstatus calls to all the pending swaps and if any are not .finished, then they are still pending.

this might be able to just query a pendingcount variable after you implement a background querying of swapstatus, but I am just guessing on that.
