### ISSUE TITLE
Buy and Sell is a little confusing

### ISSUE THREAD

**Issue by wllmcdl** [lukechilds/hyperdex#277]
I'm selling 10000 pizza to 1 beer and when I click view it's saying buy: 10000beer for:10pizza with price being 0.001

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
darwin 17.5.0
Locale: en-US

**Comment by lukechilds** [comment]
Thanks for helping us test HyperDEX and providing feedback 🙌

This is a knows issue and is due to how `marketmaker` works.

More information here:
https://github.com/lukechilds/hyperdex-bugtracker/issues/15
https://github.com/lukechilds/hyperdex/issues/184

Feel free to continue the discussion on the existing issue if you think we should change the current functionality.
