### ISSUE TITLE
Hyperdex Feedback

### ISSUE THREAD

**Issue by bmagee251** [lukechilds/hyperdex#305]
The Hyperdex application looks great. My first two atomic swaps went though within a matter of seconds. the next transaction I made went unmatched, although there were pizza sell orders on the books. The next three atomic swaps I tried went into pending. Hyperdex only allowed me to cancel one. The other two orders were stuck in pending status. I see great potential in Hyperdex, Great work.
![capture](https://user-images.githubusercontent.com/11364149/40463744-c1c95876-5ecb-11e8-94c9-5a3e5fdb7508.PNG)

![capture2](https://user-images.githubusercontent.com/11364149/40463784-03cb6a52-5ecc-11e8-94ff-4d0d87edf642.PNG)

---

HyperDEX 0.1.0-alpha.1
Electron 2.0.0
win32 10.0.17134
Locale: en-US

**Comment by lukechilds** [comment]
Thanks for your feedback!

Anything to do with matching or failed orders is to do with the underlying BarterDEX network daemon (`marketmaker`), nothing to do with the UI. We just send your input to it and display the response.

The swaps stuck in pending and un-cancelable trades are also a `marketmaker` issue. These should be fixed in `marketmaker` V2.
