### ISSUE TITLE
Enhancement - uninstall existing version upon new install

### ISSUE THREAD

**Issue by jdmarlow86** [lukechilds/hyperdex#319]
Suggest implementing an existing version uninstall consistent with Agama. When multiple versions are open MM crashes and forces an app restart.  

![image](https://user-images.githubusercontent.com/22251770/40567732-a1d9e02e-6044-11e8-88f9-1d639255d533.png)

**Comment by lukechilds** [comment]
There is no conflict when you install a new version. You can even run multiple mm instances at the same time without them crashing, it's just that only one will get access to the network.

The error you are seeing is just caused by `marketmaker` crashing which happens sometimes. Unrelated to existing installations.
